INSERT INTO WRH_UNITS (UNIT_ID, UNIT_NAME_AR, UNIT_NAME_EN) VALUES ( 1, 'حبة', 'pices' );

INSERT INTO WRH_UNITS (UNIT_ID, UNIT_NAME_AR, UNIT_NAME_EN) VALUES ( 2, 'جهاز', 'machine' );

INSERT INTO WRH_UNITS (UNIT_ID, UNIT_NAME_AR, UNIT_NAME_EN) VALUES ( 3, 'مكتب', 'office' );
