CREATE TABLE WRH_UNITS
(
    UNIT_ID  NUMBER NOT NULL auto_increment,
    UNIT_NAME_AR        VARCHAR(100),
    UNIT_NAME_EN        VARCHAR(100)
);

ALTER TABLE WRH_UNITS
    ADD PRIMARY KEY (UNIT_ID);
